export type LegalSection = {
  readonly heading: string;
  readonly paragraphs?: readonly string[];
  readonly bullets?: readonly string[];
};

export type LegalDocument = {
  readonly title: string;
  readonly description: string;
  readonly sections: readonly LegalSection[];
};

export const LEGAL_DOCUMENTS = {
  "privacy": {
    "title": "Privacy Policy",
    "description": "How MiJoy Enterprises LLC collects, uses, discloses, retains, and protects personal information through Orbital One Realty™, LunaSphere™, and LunaScape™.",
    "sections": [
      {
        "heading": "1. Scope",
        "paragraphs": [
          "This Privacy Policy applies when you visit orbitalonerealty.com, create or use an account, select or reserve a property, purchase a novelty lunar property or related product, use LunaSphere™, receive LunaScape™ content, contact us, or receive customer, HOA, or marketing communications.",
          "Third-party websites and services maintain their own privacy practices."
        ]
      },
      {
        "heading": "2. Information We Collect",
        "paragraphs": [
          "We may collect information you provide, information generated by your use of the service, and limited transaction information received from service providers."
        ],
        "bullets": [
          "Name, email address, account and authentication information",
          "Billing and contact information",
          "Deed names, gift-recipient details, gift messages, and personalization instructions",
          "Property selections, reservations, purchases, order records, and fulfillment information",
          "Customer-service communications and marketing preferences",
          "IP address, browser and device information, pages and features used, approximate region, security logs, and cookie or storage information"
        ]
      },
      {
        "heading": "3. Payment Information",
        "paragraphs": [
          "Payments are processed by Stripe. Orbital One Realty does not receive or store complete payment-card numbers or card-security codes. We may receive payment status, transaction identifiers, amount, currency, billing contact information, limited payment-method details, and fraud or risk signals."
        ]
      },
      {
        "heading": "4. How We Use Information",
        "bullets": [
          "Create and manage accounts and customer portfolios",
          "Reserve properties, process checkout, verify payment, and prevent duplicate sales",
          "Generate personalized deeds, certificates, membership materials, passports, images, and related documents",
          "Deliver purchases, gift notifications, account access, and customer support",
          "Detect fraud, abuse, security incidents, and unauthorized activity",
          "Maintain accounting, tax, legal, property-allocation, and business records",
          "Send transactional messages, HOA communications, newsletters, and permitted marketing",
          "Improve, secure, troubleshoot, and enforce the website and its policies"
        ]
      },
      {
        "heading": "5. Legal Bases for International Processing",
        "paragraphs": [
          "Where European Economic Area, United Kingdom, or similar law applies, we rely on performance of a contract, legitimate interests, consent, legal obligations, and establishment or defense of legal claims, as appropriate. Consent may be withdrawn where processing depends on consent, without affecting earlier lawful processing."
        ]
      },
      {
        "heading": "6. Gift Purchases and Other People’s Information",
        "paragraphs": [
          "When you provide another person’s information for a gift, additional deed name, passport, or personalized document, you represent that you are authorized to provide it. Gift-recipient information is used to prepare and deliver the gift and is not used for unrelated promotional marketing without an appropriate legal basis."
        ]
      },
      {
        "heading": "7. Personalized Documents and Property Content",
        "paragraphs": [
          "Generated deeds, certificates, membership materials, passports, welcome documents, property records, and LunaScape™ content may display customer-supplied names and property information. Customers are responsible for reviewing submitted personalization details. Personalized documents are not intentionally made public unless the customer shares them or authorizes publication."
        ]
      },
      {
        "heading": "8. Cookies and Similar Technologies",
        "paragraphs": [
          "We use necessary cookies, local storage, and similar technologies for account sessions, shopping carts, reservations, checkout, security, and privacy preferences. No optional analytics or advertising trackers are currently enabled on the customer-facing website. If optional tracking is introduced, it will be disclosed and, where required, disabled until consent is provided. See the Cookie Policy for the current inventory."
        ]
      },
      {
        "heading": "9. How We Disclose Information",
        "paragraphs": [
          "We may disclose information to providers that support payment processing, hosting, databases, email delivery, authentication, document generation, security, diagnostics, customer support, legal, accounting, and professional services. Current core providers include Stripe, Vercel, Neon, and Resend."
        ],
        "bullets": [
          "To comply with law, court process, or lawful government requests",
          "To protect customers, MiJoy Enterprises LLC, or others",
          "To investigate fraud, abuse, security threats, or policy violations",
          "In connection with a merger, financing, acquisition, reorganization, or sale of assets",
          "At your direction or with your consent"
        ]
      },
      {
        "heading": "10. Sale, Sharing, and Targeted Advertising",
        "paragraphs": [
          "We do not sell personal information for money and do not currently use customer-facing cross-site behavioral advertising. If practices change in a way legally treated as a sale, sharing, or targeted advertising, we will update this Policy and provide required controls. We honor legally recognized preference signals where applicable."
        ]
      },
      {
        "heading": "11. Marketing and HOA Communications",
        "paragraphs": [
          "Transactional, account, security, purchase, and fulfillment communications are necessary to provide the service. Marketing emails will include an unsubscribe method where required. Unsubscribing from marketing does not stop necessary transactional messages."
        ]
      },
      {
        "heading": "12. International Transfers",
        "paragraphs": [
          "MiJoy Enterprises LLC is based in the United States. Information may be processed in the United States or other countries where providers operate. Where required, appropriate transfer safeguards will be used."
        ]
      },
      {
        "heading": "13. Data Retention",
        "paragraphs": [
          "We retain information only as reasonably necessary for accounts, fulfillment, replacement documents, property-allocation integrity, fraud prevention, accounting, tax, legal obligations, disputes, and security. Some order and property records may be retained long term to preserve the integrity of the Orbital One property system and customer ownership history."
        ]
      },
      {
        "heading": "14. Security",
        "paragraphs": [
          "We use reasonable administrative, technical, and organizational safeguards. No system can be guaranteed completely secure. Customers are responsible for protecting account credentials and reporting suspected unauthorized access."
        ]
      },
      {
        "heading": "15. Your Privacy Rights",
        "paragraphs": [
          "Depending on where you live and whether a law applies, you may request access, correction, deletion, portability, restriction, objection, withdrawal of consent, opt-out of covered sale or sharing, or appeal of a privacy decision. Rights may be subject to lawful exceptions, including transaction completion, security, legal compliance, property-allocation integrity, and legal claims."
        ]
      },
      {
        "heading": "16. California and Other U.S. State Rights",
        "paragraphs": [
          "Where an applicable state privacy law covers MiJoy Enterprises LLC, verified requests will be handled as required and without unlawful discrimination. We do not offer financial incentives for personal information unless separately disclosed."
        ]
      },
      {
        "heading": "17. European and United Kingdom Rights",
        "paragraphs": [
          "Where GDPR, UK GDPR, or related law applies, individuals may have rights of access, correction, deletion, restriction, objection, portability, withdrawal of consent, and complaint to a data-protection authority."
        ]
      },
      {
        "heading": "18. Children’s Privacy",
        "paragraphs": [
          "The website and purchasing services are intended for adults and are not directed to children under 13. An adult may request that a child’s name appear on a gift or personalized document. If we learn that information was collected directly from a child under 13 without required authorization, we will take reasonable steps to delete it."
        ]
      },
      {
        "heading": "19. Contact and Requests",
        "paragraphs": [
          "Privacy questions and requests may be sent to mijoyenterprises@gmail.com or mailed to MiJoy Enterprises LLC at the address shown below. We may need to verify identity before completing a request. Do not send passwords, complete payment-card numbers, or unnecessary sensitive information by email."
        ]
      },
      {
        "heading": "20. Changes",
        "paragraphs": [
          "We may update this Policy to reflect changes in services, technology, vendors, law, or business practices. The revised version will be posted with a new effective date, and additional notice or consent will be provided when required."
        ]
      }
    ]
  },
  "terms": {
    "title": "Terms and Conditions",
    "description": "The contract governing access to and use of Orbital One Realty™, LunaSphere™, LunaScape™, customer accounts, purchasing services, and digital products.",
    "sections": [
      {
        "heading": "1. Agreement",
        "paragraphs": [
          "These Terms govern orbitalonerealty.com and the products and services provided by MiJoy Enterprises LLC under the Orbital One Realty™ brand. By accessing the website, creating an account, selecting a property, placing an order, checking an acceptance box, or using the services, you agree to these Terms, the Privacy Policy, Refund and Cancellation Policy, and any product-specific checkout terms."
        ]
      },
      {
        "heading": "2. Important Novelty-Property Disclosure",
        "paragraphs": [
          "Orbital One Realty sells novelty, commemorative, entertainment, and personalized digital products. A purchase does not convey legally recognized ownership of land or real estate on the Moon and is not a government-recognized deed, title, leasehold, mineral right, development right, occupancy right, investment, security, or financial instrument."
        ],
        "bullets": [
          "No right to occupy, visit, develop, control, or exclude others from a lunar location",
          "No claim enforceable against a government, space agency, international organization, company, or other person",
          "No promise of resale, investment, development, or future financial value"
        ]
      },
      {
        "heading": "3. No Government or Third-Party Affiliation",
        "paragraphs": [
          "MiJoy Enterprises LLC and Orbital One Realty are private commercial entities and are not affiliated with, sponsored by, approved by, licensed by, or endorsed by NASA, any government or space agency, the United Nations, any scientific institution, aerospace company, historical mission, astronaut, estate, or foundation unless expressly stated."
        ]
      },
      {
        "heading": "4. Eligibility",
        "paragraphs": [
          "You must be at least 18 or the age of legal majority where you live and have legal capacity to enter a contract. An adult may purchase a novelty property or personalized product as a gift for a minor."
        ]
      },
      {
        "heading": "5. Accounts",
        "paragraphs": [
          "You are responsible for accurate account information, access to your email, safeguarding credentials, and promptly reporting suspected unauthorized activity. Accounts may be restricted when reasonably necessary for security, fraud, payment disputes, abuse, or Terms violations."
        ]
      },
      {
        "heading": "6. LunaSphere™ and LunaScape™",
        "paragraphs": [
          "LunaSphere™ is Orbital One Realty’s proprietary novelty lunar-geography, inventory, identification, reservation, search, and visualization system. LunaScape™ is a branded visual and experiential concept. Maps, boundaries, sizes, coordinates, distances, and visualizations may be approximate, stylized, scaled, projected, or adapted for technical and entertainment purposes and are not official legal, cadastral, scientific, surveying, or navigational records."
        ]
      },
      {
        "heading": "7. Availability and Reservations",
        "paragraphs": [
          "Properties are subject to availability. Adding a property to a cart or beginning checkout does not complete a purchase. Reservations are temporary, may expire, and may be released or canceled for inventory conflicts, errors, payment failure, fraud concerns, security issues, or expiration. An order is complete only after successful payment, order acceptance, and confirmation or account recording."
        ]
      },
      {
        "heading": "8. Selection Methods",
        "paragraphs": [
          "Property selection may occur through the Moon Map, Search and Fly-To Navigation, Quick Pick, or other disclosed methods. Quick Pick selects from currently available inventory in the chosen category and does not guarantee a specific location unless expressly confirmed."
        ]
      },
      {
        "heading": "9. Prices, Currency, and Taxes",
        "paragraphs": [
          "Prices are generally shown in U.S. dollars and confirmed at final checkout. Taxes may be added when required. Banks and payment providers may charge conversion or foreign-transaction fees. We may correct pricing, calculation, inventory, or typographical errors before fulfillment and will provide an appropriate remedy for a material error affecting a paid order."
        ]
      },
      {
        "heading": "10. Payments and Order Acceptance",
        "paragraphs": [
          "Payments are processed by Stripe or another disclosed provider. You represent that you are authorized to use the payment method and authorize the charges. Payment authorization does not guarantee acceptance. We may refuse, limit, hold, or cancel an order for inventory conflicts, pricing errors, payment problems, fraud, legal restrictions, technical issues, or Terms violations."
        ]
      },
      {
        "heading": "11. Digital Fulfillment",
        "paragraphs": [
          "Products are primarily personalized digital products unless a listing states otherwise. Delivery may occur through an account, download page, email, secure link, or another disclosed electronic method. Delivery is completed when the content is made available through the stated method. Customers are responsible for accurate email information, compatible technology, checking filtered folders, and retaining copies."
        ]
      },
      {
        "heading": "12. Immediate Performance",
        "paragraphs": [
          "By completing checkout, you request prompt property assignment, recording, document generation, account fulfillment, image preparation, and digital delivery. Where a withdrawal right applies, a separate express consent may be required before performance begins and may cause that right to be reduced or lost once performance or delivery starts. Non-waivable consumer rights remain unaffected."
        ]
      },
      {
        "heading": "13. Personalization and Gifts",
        "paragraphs": [
          "You are responsible for spelling, capitalization, punctuation, names, email addresses, gift messages, and selections. We may reject unlawful, hateful, threatening, deceptive, infringing, or inappropriate personalization. A purchaser providing another person’s information represents authority to do so and remains responsible for the order."
        ]
      },
      {
        "heading": "14. Refunds and Cancellations",
        "paragraphs": [
          "Because products are personalized and digital production may begin immediately, orders are generally final after production or fulfillment begins. The Refund and Cancellation Policy controls refund requests and is incorporated into these Terms. Nothing limits a mandatory consumer right that cannot lawfully be waived."
        ]
      },
      {
        "heading": "15. HOA Membership",
        "paragraphs": [
          "A qualifying purchase may include complimentary 2026 Charter HOA membership. This is a novelty, promotional, customer, and community program—not a statutory homeowners’ association. It creates no real-property covenants, assessments, liens, voting districts, or governmental authority. Benefits may evolve, be delayed, replaced, or discontinued and have no cash value."
        ]
      },
      {
        "heading": "16. Future Features",
        "paragraphs": [
          "Statements about virtual homes, enhancements, communities, member recognition, discounts, LunaSphere™, or LunaScape™ features describe plans or possibilities, not binding promises. No purchase guarantees a launch date, continued availability, compatibility, design, functionality, commercial value, or resale value."
        ]
      },
      {
        "heading": "17. Customer License",
        "paragraphs": [
          "Customers receive a limited, non-exclusive, non-transferable, revocable license to use purchased materials personally and noncommercially. Customers may download, print, display, and share reasonable personal copies or gifts, but may not resell, mass reproduce, remove disclaimers, misrepresent legal title, create competing products, scrape data, reverse engineer systems, or use materials in tokens, NFTs, financial products, registries, or other commercial offerings without written permission."
        ]
      },
      {
        "heading": "18. Intellectual Property",
        "paragraphs": [
          "The website, software, code, designs, text, graphics, maps, grids, documents, images, logos, property-identification systems, databases, selection methods, and other content are owned by or licensed to MiJoy Enterprises LLC. Orbital One Realty™, LunaSphere™, and LunaScape™ are trademarks claimed by MiJoy Enterprises LLC. All ungranted rights are reserved."
        ]
      },
      {
        "heading": "19. Prohibited Conduct",
        "bullets": [
          "Unlawful, fraudulent, deceptive, abusive, threatening, or infringing activity",
          "Misrepresentation of novelty products as legally recognized lunar titles",
          "Manipulation of reservations, inventory, checkout, payment, fulfillment, accounts, or security controls",
          "Unauthorized bots, scraping, reverse engineering, vulnerability probing, malware, or denial-of-service activity",
          "Unauthorized commercial copying or use of Orbital One intellectual property",
          "False identity, payment, personalization, or gift-recipient information"
        ]
      },
      {
        "heading": "20. Third-Party Services",
        "paragraphs": [
          "The services may rely on payment, hosting, database, email, authentication, security, analytics, and other providers. Third-party services are governed by their own terms and policies. We are not responsible for matters outside our control, subject to non-waivable law."
        ]
      },
      {
        "heading": "21. Availability and Changes",
        "paragraphs": [
          "The website may be unavailable for maintenance, updates, security, outages, legal requirements, or events beyond reasonable control. We may update, suspend, replace, restrict, or discontinue features. Customers should retain their own copies of delivered materials."
        ]
      },
      {
        "heading": "22. Warranty Disclaimer",
        "paragraphs": [
          "TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE WEBSITE, SERVICES, MAPS, PRODUCTS, MEMBERSHIPS, DOCUMENTS, IMAGES, AND CONTENT ARE PROVIDED “AS IS” AND “AS AVAILABLE.” MIJOY ENTERPRISES LLC DISCLAIMS WARRANTIES NOT EXPRESSLY PROVIDED IN WRITING, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, AND AVAILABILITY. Mandatory warranties that cannot be excluded remain applicable."
        ]
      },
      {
        "heading": "23. Limitation of Liability",
        "paragraphs": [
          "TO THE MAXIMUM EXTENT PERMITTED BY LAW, MIJOY ENTERPRISES LLC AND ITS OWNERS, MANAGERS, EMPLOYEES, CONTRACTORS, LICENSORS, AND PROVIDERS WILL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES. TOTAL LIABILITY ARISING FROM A PARTICULAR ORDER OR USE OF THE SERVICES WILL NOT EXCEED THE AMOUNT PAID FOR THE TRANSACTION GIVING RISE TO THE CLAIM. This does not exclude fraud, intentional misconduct, or liability that cannot lawfully be limited."
        ]
      },
      {
        "heading": "24. Indemnification",
        "paragraphs": [
          "To the maximum extent permitted by law, you agree to indemnify MiJoy Enterprises LLC and related persons from claims and reasonable costs arising from your unlawful use, violation of these Terms, misuse or resale of novelty documents, infringement, unauthorized gift-recipient information, or representation that an Orbital One product creates legally recognized lunar ownership, except to the extent caused by our own unlawful conduct."
        ]
      },
      {
        "heading": "25. International Customers",
        "paragraphs": [
          "Services are operated from the United States. International customers are responsible for local legality, sanctions, export restrictions, payment restrictions, and compatible technology. Florida law does not deprive a consumer of mandatory protections that cannot be waived. The English version controls to the extent permitted by law."
        ]
      },
      {
        "heading": "26. Electronic Communications",
        "paragraphs": [
          "You consent to receive agreements, policies, confirmations, disclosures, notices, and records electronically and confirm that you can access, download, save, and print them. Electronic checkout actions and acceptance may serve as your signature."
        ]
      },
      {
        "heading": "27. Suspension and Termination",
        "paragraphs": [
          "We may suspend or terminate access for Terms violations, fraud, payment disputes, security threats, abuse, or legal obligations. Provisions concerning payment, intellectual property, misuse, liability, and dispute resolution survive as appropriate."
        ]
      },
      {
        "heading": "28. Governing Law and Venue",
        "paragraphs": [
          "These Terms are governed by Florida law without regard to conflict-of-law principles. The United Nations Convention on Contracts for the International Sale of Goods does not apply. Unresolved disputes must be brought in a state court of competent jurisdiction in Collier County, Florida, or the United States District Court for the Middle District of Florida when federal jurisdiction exists, subject to mandatory consumer-forum rights. Eligible individual claims may be brought in small-claims court. Parties will first make a reasonable good-faith effort to resolve disputes informally."
        ]
      },
      {
        "heading": "29. General Provisions",
        "paragraphs": [
          "Unauthorized use of intellectual property, confidential systems, customer information, or security controls may support injunctive relief. If a provision is unenforceable, the remaining provisions continue. Failure to enforce is not a waiver. You may not assign these Terms without permission; MiJoy Enterprises LLC may assign them in a business transaction. These Terms and incorporated policies form the entire agreement for the services."
        ]
      },
      {
        "heading": "30. Contact",
        "paragraphs": [
          "Questions may be sent to mijoyenterprises@gmail.com or mailed to MiJoy Enterprises LLC at the address shown below. Do not send passwords, complete payment-card information, or unnecessary sensitive information by email."
        ]
      }
    ]
  },
  "refunds": {
    "title": "Refund and Cancellation Policy",
    "description": "When personalized digital orders may be cancelled, corrected, replaced, or refunded.",
    "sections": [
      {
        "heading": "1. Personalized Digital Products",
        "paragraphs": [
          "Most Orbital One Realty products are personalized and digitally fulfilled. They may include deeds, certificates, property records, welcome letters, HOA materials, passports, terrain images, LunaScape™ images, gift materials, and account portfolio records. Orders are generally final once personalized production or fulfillment begins."
        ]
      },
      {
        "heading": "2. Immediate Fulfillment",
        "paragraphs": [
          "Processing may begin immediately after payment and may include assigning or confirming a property, marking it sold, creating records, generating documents and images, updating the account portfolio, and sending fulfillment communications."
        ]
      },
      {
        "heading": "3. Cancellation Before Production",
        "paragraphs": [
          "You may request cancellation before production begins by emailing mijoyenterprises@gmail.com with the purchaser name, email, order number, property identifier, and reason. A request does not guarantee cancellation if production, assignment, recording, or delivery has already started."
        ]
      },
      {
        "heading": "4. Refunds We May Approve",
        "bullets": [
          "Verified duplicate charges",
          "Orbital One cannot deliver the purchased product",
          "Orbital One cancels a paid order before fulfillment",
          "A material technical failure cannot reasonably be corrected",
          "A materially defective file cannot be repaired or replaced",
          "A material Orbital One pricing, assignment, personalization, or fulfillment error",
          "An inventory conflict affects a paid order",
          "A refund is required by law",
          "Another exceptional circumstance warrants a refund in our reasonable discretion"
        ]
      },
      {
        "heading": "5. Generally Nonrefundable Circumstances",
        "bullets": [
          "A change of mind after personalized production begins",
          "Expecting legally recognized lunar real-estate ownership",
          "Overlooking or misunderstanding the novelty disclosure",
          "Customer-entered spelling, name, email, message, or selection errors",
          "Preferring another property after assignment or recording",
          "A gift recipient does not want the gift",
          "Failure to download, retain, open, or print delivered files",
          "Email filtering, customer-controlled inbox problems, or incompatible technology",
          "Expected resale, investment, development, occupancy, mineral, or financial value",
          "Changes, delays, or non-release of future features or complimentary benefits",
          "Bank, currency-conversion, overdraft, or foreign-transaction fees"
        ]
      },
      {
        "heading": "6. Customer-Supplied Errors",
        "paragraphs": [
          "Contact us immediately after discovering an error. We may correct an unfulfilled order when possible. Corrections after generation or delivery may require a fee unless Orbital One caused the error."
        ]
      },
      {
        "heading": "7. Duplicate Charges",
        "paragraphs": [
          "Verified duplicate payment for the same transaction will be refunded to the original payment method. Separate valid property purchases are not duplicate charges merely because they share a price or were made close together."
        ]
      },
      {
        "heading": "8. Inventory Conflicts",
        "paragraphs": [
          "If a technical or inventory conflict affects a paid order, we may offer a comparable property with approval, allow replacement selection, refund the affected item, or cancel and refund the affected portion. Verified reservation, payment, inventory, and order records control the investigation."
        ]
      },
      {
        "heading": "9. Defective or Missing Files",
        "paragraphs": [
          "We will first attempt repair, regeneration, replacement, redelivery, or an accessible alternative. A refund may be considered only when the purchased content cannot reasonably be repaired, regenerated, replaced, or delivered."
        ]
      },
      {
        "heading": "10. Delivery Problems",
        "paragraphs": [
          "Before requesting a refund for non-delivery, check the account, the checkout email address, spam and junk folders, inbox capacity, and contact us for redelivery. Filtering, deletion, or an incorrect customer-entered address does not automatically make a purchase refundable."
        ]
      },
      {
        "heading": "11. Add-Ons and HOA",
        "paragraphs": [
          "Passports, additional deed names, gift messages, and other personalized add-ons follow the same final-sale rules once production begins. Complimentary HOA membership has no separately refundable cash value."
        ]
      },
      {
        "heading": "12. Chargebacks",
        "paragraphs": [
          "Please contact us before initiating a chargeback so we can investigate. A dispute does not automatically cancel fulfillment or release a property. A reversed, unauthorized, or fraudulent payment may result in account restriction, order review, benefit suspension, and return of the property to inventory when legally and technically appropriate."
        ]
      },
      {
        "heading": "13. Approved Refunds",
        "paragraphs": [
          "Approved refunds are ordinarily returned to the original payment method. Processing time depends on Stripe, the card issuer, bank, currency, and country. We do not control foreign-exchange differences or third-party fees. Partial refunds may be used when only part of an order is affected."
        ]
      },
      {
        "heading": "14. International Rights",
        "paragraphs": [
          "Mandatory cancellation, withdrawal, conformity, warranty, or refund rights remain applicable. Where lawful, we request express consent to immediate personalized digital performance and acknowledgment that an applicable withdrawal right may be lost after performance or delivery begins."
        ]
      },
      {
        "heading": "15. Fraud and Abuse",
        "paragraphs": [
          "We may deny requests supported by evidence of fraud, false statements, inventory manipulation, refund abuse, repeated download-and-refund activity, chargeback abuse, or attempts to retain products without payment, subject to non-waivable rights."
        ]
      },
      {
        "heading": "16. Contact and Changes",
        "paragraphs": [
          "Send requests to mijoyenterprises@gmail.com with the order number and purchaser email. The version in effect when an order is placed generally governs that order. Updated versions will be posted with a new effective date."
        ]
      }
    ]
  },
  "cookies": {
    "title": "Cookie Policy",
    "description": "The current inventory of cookies, browser storage, and similar technologies used by Orbital One Realty™.",
    "sections": [
      {
        "heading": "1. Current Status",
        "paragraphs": [
          "The customer-facing website currently uses only technologies needed for accounts, carts, property reservations, checkout, security, and privacy preferences. It does not currently load optional customer-facing analytics, advertising pixels, or cross-site behavioral trackers."
        ]
      },
      {
        "heading": "2. What These Technologies Are",
        "paragraphs": [
          "Cookies are small files stored by a browser. Similar technologies include local storage, session tokens, scripts, identifiers, server logs, and consent-preference records. We refer to them collectively as cookies and similar technologies."
        ]
      },
      {
        "heading": "3. Strictly Necessary Inventory",
        "bullets": [
          "oor_customer_session_v2 — Orbital One first-party, HTTP-only account-session cookie; necessary for secure customer login; up to 7 days",
          "orbital_one_cart_reservations — Orbital One first-party cart-reservation cookie; necessary to maintain reserved property IDs and checkout continuity; up to 7 days",
          "orbital-one-cart — Orbital One browser local-storage record; necessary to maintain cart selections and options until cleared or expired",
          "orbital-one-cookie-preferences — Orbital One browser local-storage record; remembers that the cookie notice was reviewed and the current policy version",
          "Stripe-hosted checkout technologies — controlled by Stripe after checkout handoff for payment operation, fraud prevention, security, and regulatory compliance"
        ]
      },
      {
        "heading": "4. Purposes",
        "bullets": [
          "Keep items and reservation IDs associated with a cart",
          "Maintain secure login sessions",
          "Protect accounts, checkout, and transaction integrity",
          "Prevent duplicate sales and fraudulent activity",
          "Remember privacy choices",
          "Process payment and fulfillment"
        ]
      },
      {
        "heading": "5. Optional Categories",
        "paragraphs": [
          "Functional, analytics, performance, advertising, and targeting technologies are not currently enabled on the customer-facing site. If introduced, this Policy and the preferences interface will identify the provider, purpose, category, and duration. Where required, optional technologies will remain disabled until valid consent is provided."
        ]
      },
      {
        "heading": "6. Stripe",
        "paragraphs": [
          "Stripe may use cookies and similar technologies on its hosted checkout for payment processing, authentication, fraud prevention, risk analysis, security, and compliance. Stripe’s own terms and privacy notices govern its independent processing."
        ]
      },
      {
        "heading": "7. Choices",
        "paragraphs": [
          "Strictly necessary technologies cannot be disabled through our settings because the requested service may not function without them. You may clear or block them through browser controls, but doing so may prevent login, cart use, reservations, checkout, or privacy-preference storage. A permanent Cookie Settings control is available in the website footer."
        ]
      },
      {
        "heading": "8. Browser Controls and Signals",
        "paragraphs": [
          "Browsers may allow cookie viewing, deletion, blocking, local-storage clearing, and tracking restrictions. Where applicable law requires it, we will honor a recognized Global Privacy Control signal for covered sale, sharing, or targeted advertising. We do not currently conduct those activities. Conventional Do Not Track signals may not be recognized because no universal standard exists."
        ]
      },
      {
        "heading": "9. Retention and Security",
        "paragraphs": [
          "Session and storage duration depends on purpose. We use durations reasonably necessary for login, reservations, carts, security, and preferences. No browser, device, website, transmission, or storage technology can be guaranteed completely secure."
        ]
      },
      {
        "heading": "10. International Visitors",
        "paragraphs": [
          "Where optional technologies are introduced and consent is required, they will not load before an affirmative choice, optional categories will be off by default, rejection will not block essential services, and withdrawal will be as easy as acceptance."
        ]
      },
      {
        "heading": "11. Changes and Contact",
        "paragraphs": [
          "We may update this Policy when technologies, providers, purposes, retention periods, or laws change. Questions may be sent to mijoyenterprises@gmail.com."
        ]
      }
    ]
  },
  "accessibility": {
    "title": "Accessibility Statement",
    "description": "Orbital One Realty’s ongoing commitment to accessible website, map, account, checkout, and digital-document experiences.",
    "sections": [
      {
        "heading": "1. Commitment and Goal",
        "paragraphs": [
          "MiJoy Enterprises LLC is committed to making orbitalonerealty.com, LunaSphere™, LunaScape™, and the digital purchasing experience accessible to as many people as reasonably possible. We are working toward substantial conformance with WCAG 2.2 Level AA. Accessibility is ongoing, and we do not claim that every page, file, feature, or third-party service is barrier-free."
        ]
      },
      {
        "heading": "2. Measures",
        "bullets": [
          "Logical headings, descriptive titles, meaningful labels, and alternative text",
          "Keyboard-accessible navigation and visible focus",
          "Sufficient contrast and responsive layouts",
          "Labeled forms, instructions, and understandable errors",
          "Reduced reliance on color alone",
          "Accessible account, cart, checkout, policy, and support paths",
          "Testing with keyboard navigation, zoom, screen readers, and mobile accessibility features"
        ]
      },
      {
        "heading": "3. LunaSphere™ Map",
        "paragraphs": [
          "Interactive maps can be challenging for screen-reader, keyboard-only, voice-control, and magnification users. We seek to provide keyboard controls, search-based navigation, text labels, property identifiers, status information, property-detail panels, non-color indicators, and customer-service assistance. Assistance does not guarantee availability or bypass reservation, pricing, payment, or inventory controls."
        ]
      },
      {
        "heading": "4. Digital Documents and Images",
        "paragraphs": [
          "Decorative deeds, certificates, passports, terrain images, and LunaScape™ scenes may not be fully optimized for every assistive technology. Customers may request a plain-text version, simplified summary, improved-reading-order PDF, visual description, or another reasonably available format. The accessible alternative may differ visually while preserving essential information."
        ]
      },
      {
        "heading": "5. Forms, Accounts, and Checkout",
        "paragraphs": [
          "We seek visible labels, required-field indicators, understandable validation, reasonable completion time, accessible policy links and acknowledgments, clear totals, and clear confirmation. Stripe-hosted checkout accessibility also depends on Stripe’s technology."
        ]
      },
      {
        "heading": "6. Third Parties and Compatibility",
        "paragraphs": [
          "We do not control every third-party accessibility feature. We consider accessibility when reviewing important providers and will investigate barriers. The site is intended for current common browsers, operating systems, and assistive technologies; outdated or unusual combinations may reduce compatibility."
        ]
      },
      {
        "heading": "7. Known Potential Limitations",
        "bullets": [
          "Complex Moon-map interactions and parcel-grid selection",
          "Highly visual lunar geography",
          "Decorative or image-based generated PDFs",
          "Text embedded in certain images",
          "Third-party checkout or authentication interfaces",
          "Status messages, mobile touch targets, and older content requiring continued testing"
        ]
      },
      {
        "heading": "8. Alternative Access",
        "paragraphs": [
          "If a barrier prevents access to information, selection, purchase, or delivery, contact us. We will make reasonable efforts to provide another format, explain property information, assist with navigation, locate an available property, regenerate a document, or offer another reasonable method."
        ]
      },
      {
        "heading": "9. Feedback",
        "paragraphs": [
          "Email mijoyenterprises@gmail.com with the subject “Accessibility Request — Orbital One Realty.” Include the page or feature, the problem, device and browser, assistive technology if relevant, and the alternative that would help. Do not include passwords, full payment-card information, medical information, or unnecessary sensitive information."
        ]
      },
      {
        "heading": "10. Continuous Improvement",
        "paragraphs": [
          "Our work may include automated and manual testing, keyboard and screen-reader review, contrast and zoom testing, mobile testing, PDF review, remediation, and customer feedback. We will not intentionally reduce service or retaliate because a customer uses assistive technology or requests assistance."
        ]
      }
    ]
  },
  "legalNotice": {
    "title": "Website Legal Notice and Intellectual Property Policy",
    "description": "Ownership, trademark, copyright, attribution, permitted use, and novelty-property notices for Orbital One Realty™, LunaSphere™, and LunaScape™.",
    "sections": [
      {
        "heading": "1. Website Operator",
        "paragraphs": [
          "The website and related services are owned and operated by MiJoy Enterprises LLC under the Orbital One Realty™ brand."
        ]
      },
      {
        "heading": "2. Claimed Trademarks",
        "paragraphs": [
          "Orbital One Realty™, LunaSphere™, and LunaScape™ are trademarks claimed by MiJoy Enterprises LLC. The ™ symbol indicates claimed rights and does not mean federal registration. The ® symbol must not be used unless the particular mark is registered for the applicable goods or services."
        ]
      },
      {
        "heading": "3. Protected Brand Elements",
        "paragraphs": [
          "Protected elements may include names, logos, slogans, taglines, color combinations, graphics, document designs, maps, property-identification systems, badges, terminology, and marketing. “It’s fun. It’s unique. It’s out of this world!” is used as an Orbital One Realty brand element."
        ]
      },
      {
        "heading": "4. Copyright",
        "paragraphs": [
          "Unless otherwise identified, original website text, layouts, graphics, artwork, photographs, illustrations, videos, documents, templates, maps, software, code, databases, emails, and compilations are owned by or licensed to MiJoy Enterprises LLC and protected by applicable law. © 2026 MiJoy Enterprises LLC. All rights reserved."
        ]
      },
      {
        "heading": "5. Proprietary Systems",
        "paragraphs": [
          "LunaSphere™ includes proprietary geography, inventory, identifiers, grids, search, reservation logic, availability status, databases, administrative tools, and presentation. LunaScape™ includes proprietary visual styles, virtual-property presentations, environment concepts, artwork, interfaces, software, and possible future experiences. Using or purchasing through the site does not transfer ownership of these systems."
        ]
      },
      {
        "heading": "6. Limited Personal Use",
        "paragraphs": [
          "Visitors may view public content for personal, lawful, noncommercial purposes. Customers may download, print, display, retain, and reasonably share purchased materials for personal use or with the intended gift recipient, subject to the Terms. No intellectual-property ownership is transferred."
        ]
      },
      {
        "heading": "7. Prohibited Use",
        "bullets": [
          "Copying substantial portions of the website or reselling documents or templates",
          "Republishing, scraping, compiling, or reverse engineering LunaSphere™ maps, identifiers, grids, availability, databases, software, or fulfillment systems",
          "Removing legal, novelty, copyright, or trademark notices",
          "Representing novelty documents as government-issued or legally recognized titles",
          "Registering or using confusingly similar domains, accounts, brands, metadata, or advertising",
          "Using content in a competing business, NFT, token, cryptocurrency, financial product, registry, or title system",
          "Claiming sponsorship, endorsement, partnership, or authorization that does not exist"
        ]
      },
      {
        "heading": "8. Customer Content",
        "paragraphs": [
          "Customers retain rights in original names, messages, photographs, or other content they submit. They grant MiJoy Enterprises LLC a limited license to use it for order processing, personalization, delivery, accounts, support, corrections, and necessary records and represent that such use is lawful."
        ]
      },
      {
        "heading": "9. Artistic and Generated Imagery",
        "paragraphs": [
          "Some images may be artistic renderings, composites, computer-generated or AI-assisted images, digitally enhanced views, simulated environments, or conceptual LunaScape™ scenes. They are not proof of physical construction, current possession, scientific precision, government records, or legal title."
        ]
      },
      {
        "heading": "10. Lunar Information",
        "paragraphs": [
          "Public lunar names, facts, coordinates, mission information, and public-domain material are not claimed exclusively. MiJoy Enterprises LLC may claim rights in its original selection, organization, presentation, descriptions, property divisions, naming systems, database arrangement, software, and entertainment experience."
        ]
      },
      {
        "heading": "11. Novelty Property Notice",
        "paragraphs": [
          "Orbital One products do not convey government-recognized title, legal real-estate ownership, sovereignty, leasehold, possession, mineral rights, development rights, occupancy rights, exclusion rights, investment interests, securities, or financial instruments. They exist only within the Orbital One customer and entertainment experience."
        ]
      },
      {
        "heading": "12. NASA, Apollo, and Third Parties",
        "paragraphs": [
          "Orbital One Realty is not affiliated with or endorsed by NASA, any government, space agency, the United Nations, official registry, historical mission, astronaut or estate, or aerospace company. References are factual, historical, descriptive, educational, geographic, or entertainment uses. NASA insignia, seals, logotypes, and protected identifiers may not be used as Orbital One branding or to imply endorsement. Third-party marks and media remain owned by their respective owners and are used only under applicable permission, license, public-domain status, or law."
        ]
      },
      {
        "heading": "13. Links and Attribution",
        "paragraphs": [
          "Third-party links do not imply endorsement or partnership. A lawful, accurate link to a public Orbital One page is permitted if it does not frame the site deceptively or suggest a nonexistent relationship. Required source credits should appear near the material or on an attribution page."
        ]
      },
      {
        "heading": "14. Copyright and Trademark Concerns",
        "paragraphs": [
          "Send concerns to mijoyenterprises@gmail.com with the subject “Copyright Concern — Orbital One Realty” or “Trademark Concern — Orbital One Realty.” Identify the work or mark, owner, disputed use, page, basis of the claim, contact information, and authority to act. This procedure does not state that MiJoy Enterprises LLC has registered a DMCA agent."
        ]
      },
      {
        "heading": "15. Enforcement and Changes",
        "paragraphs": [
          "We may request removal, restrict abusive access, preserve evidence, report deceptive listings or accounts, send notices, seek injunctive relief, or pursue other remedies. Failure to enforce once is not a waiver. This Policy may be updated when branding, ownership, media, technology, law, or business practices change."
        ]
      }
    ]
  },
  "shippingDelivery": {
    "title": "Shipping and Digital Delivery Policy",
    "description": "How personalized Orbital One Realty digital products are processed, delivered, retained, repaired, and redelivered.",
    "sections": [
      {
        "heading": "1. Digital-First Products",
        "paragraphs": [
          "Orbital One Realty primarily sells personalized digital novelty products, including deeds, certificates, property records, welcome letters, HOA materials, passports, terrain images, LunaScape™ images, maps, gift materials, confirmations, and account portfolio records. Unless a listing expressly states otherwise, no physical item is shipped."
        ]
      },
      {
        "heading": "2. Fulfillment Start",
        "paragraphs": [
          "Fulfillment may begin after payment confirmation, inventory and reservation verification, security review, and order acceptance. It may include converting reservations, recording a sale, creating orders and account records, generating documents and images, and sending communications."
        ]
      },
      {
        "heading": "3. Delivery Methods",
        "paragraphs": [
          "Delivery may occur through a customer account, secure download page, success-page link, email attachment, secure email link, gift-recipient email, or another method disclosed at checkout. Different files may use different methods."
        ]
      },
      {
        "heading": "4. Order Confirmation",
        "paragraphs": [
          "The electronic confirmation may include order number, customer and gift details, property identifiers and types, acreage or block information, itemized prices, payment status, links, policy references, and the accepted policy version. It is not a government record or legally recognized lunar title."
        ]
      },
      {
        "heading": "5. Timing",
        "paragraphs": [
          "Some materials may be immediate while others require automated processing. Payment review, inventory checks, document or image generation, provider delays, maintenance, high volume, manual review, technical failures, or events beyond reasonable control may delay delivery. A brief delay does not mean the order failed."
        ]
      },
      {
        "heading": "6. Completion of Delivery",
        "paragraphs": [
          "Digital delivery is completed when content is made available in the account, a working link is displayed or supplied, content is sent to the provided email, a gift notification is sent, or content is otherwise electronically accessible through the disclosed method, subject to mandatory law."
        ]
      },
      {
        "heading": "7. Customer Responsibilities",
        "bullets": [
          "Provide and maintain an accurate email address",
          "Protect account credentials and report unauthorized access",
          "Check spam, junk, promotions, and filtered folders",
          "Use compatible devices, browsers, internet, and software",
          "Download and securely retain purchased files",
          "Keep backup copies rather than relying on permanent hosting"
        ]
      },
      {
        "heading": "8. Personalized Information",
        "paragraphs": [
          "Customers must review names, addresses, messages, spelling, capitalization, punctuation, and selections. Contact us promptly about errors. Corrections after generation may require a fee unless Orbital One caused the error."
        ]
      },
      {
        "heading": "9. File Formats and Accessibility",
        "paragraphs": [
          "Files may be PDF, PNG, JPEG, web content, or another common format. A current browser or PDF reader may be required. Customers encountering an accessibility barrier may request a reasonably available alternative under the Accessibility Statement."
        ]
      },
      {
        "heading": "10. Electronic Records",
        "paragraphs": [
          "Customers consent to electronic policies, disclosures, confirmations, receipts, and purchase materials and should be able to view, download, save, and print them. Customers should retain confirmations, receipts, policy versions, property identifiers, and purchased files."
        ]
      },
      {
        "heading": "11. Missing or Defective Delivery",
        "paragraphs": [
          "Before reporting non-delivery, confirm payment, review the success page and account, check the checkout email and filtered folders, verify inbox capacity, and allow reasonable processing time. We may redeliver, regenerate, repair, replace, or provide another format. A refund may be considered when content cannot reasonably be delivered or corrected."
        ]
      },
      {
        "heading": "12. Reservation and Payment Review",
        "paragraphs": [
          "An expired reservation creates no delivery obligation. An order may be held for payment risk, unauthorized activity, inconsistent information, duplicate sessions, inventory conflicts, security concerns, or legal restrictions. We will not request a complete card number, security code, or password by email."
        ]
      },
      {
        "heading": "13. International Delivery",
        "paragraphs": [
          "International customers are responsible for local legality, supported payment, internet and email access, compatible software, accurate information, and bank or currency fees. Physical customs charges generally do not apply to digital-only orders. Taxes may be collected when required. Mandatory local rights remain unaffected."
        ]
      },
      {
        "heading": "14. Future Physical Products",
        "paragraphs": [
          "A future physical listing will separately disclose destinations, processing and shipping estimates, cost, tracking, carrier, restrictions, customs, damage and loss procedures, returns, and product-specific terms. Physical delivery is not included unless expressly stated."
        ]
      },
      {
        "heading": "15. No Physical Lunar Delivery",
        "paragraphs": [
          "Digital delivery does not transfer physical possession of lunar land, record a legal deed, issue government title, transport an object to the Moon, or create recognition by a court, government, agency, or international organization."
        ]
      },
      {
        "heading": "16. Contact and Changes",
        "paragraphs": [
          "For delivery assistance, email mijoyenterprises@gmail.com with the subject “Order Delivery Assistance — Orbital One Realty,” order number, and purchaser email. Do not send passwords or complete payment-card information. The version in effect when the order is placed generally governs that order."
        ]
      }
    ]
  }
} as const satisfies Record<string, LegalDocument>;
